### ISSUE TITLE
Prepare the application for Symfony 3

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-demo#248]
We don't need to update the Symfony Demo app as soon as Symfony 3 is released, but we need to prepare the application anyway.

TODO list

* [x] Don't use the deprecated "_self" variable in Twig templates (#242)
* [x] Remove YAML configuration files deprecations (#246)
* [x] Fix the Form component deprecations for Symfony 3 (#250)
* [x] Fix the deprecations related to ResourceInterface::isFresh() (#251)
* [x] Fix the CSRF token generator deprecation (#274)
* [ ] Update the use of `_self` in Twig templates (#322)
* [ ] ...

**Comment by jzawadzki** [comment]
I would add moving to symfony3 directory structure?

**Comment by ogizanagi** [comment]
See #274 about another issue we'll encounter in 3.0.

**Comment by WouterJ** [comment]
The first item can be removed, `_self` is no longer deprecated in Twig. (this didn't have anything to do with Symfony 3 btw)

**Comment by WouterJ** [comment]
Item 3 is fixed by https://github.com/symfony/symfony-demo/pull/253

**Comment by WouterJ** [comment]
Item 4 is related to Assetic and not this app: https://github.com/symfony/symfony-demo/issues/251

**Comment by Tobion** [comment]
Unless something new migration problems come up, this issue can be closed as all those issues above have been solved.

**Comment by Tobion** [comment]
The lock file needs to be updated for assetic.

**Comment by radykal-com** [comment]
Hello,
#242 can be marked as done in the checklist as the featured was un-deprecated and the issue itself is closed.

**Comment by radykal-com** [comment]
Same with #251 the tag 2.8 from assetic bundle from 12 days ago fixed it.

**Comment by javiereguiluz** [comment]
@radykal-com good catches! Everything on the list is now marked as "fixed",so I'm closing this issue. Thanks!

**Comment by voronkovich** [comment]
@javiereguiluz, you forgot that since Symfony 3 the `_self` variable contains a string, not an instance of a template. We must fix it.

**Comment by javiereguiluz** [comment]
@voronkovich you are right. Created #322 and reopened this. Thanks!

**Comment by stof** [comment]
@voronkovich ``_self`` has nothing to do with the Symfony version. It is about Twig 2 (which is not yet released, so migrating to Symfony 3 now would still use Twig 1.x)

**Comment by stof** [comment]
@javiereguiluz please close this issue again

**Comment by javiereguiluz** [comment]
OK. Closing again and changing the new issue.
